version: '3.7'

services:
  test:
    build: ./src
    command: pytest
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - DATABASE_URL=postgresql://user_test:password_test@db-test/db_test
    depends_on:
      - db-test
    networks:
      - db_nw

  db-test:
    image: postgres:12.1-alpine
    networks:
      - db_nw
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_test
      - POSTGRES_PASSWORD=password_test
      - POSTGRES_DB=db_test

volumes:
  postgres_test_data:

networks:
  db_nw:
    driver: bridge
